### ISSUE TITLE
Scoring table

### ISSUE THREAD

**Issue by ghost** [Deadpool2468/minicoopers#11]
As you said, the table spacing isn't great.  The member name is too close to the clan name - especially for the Campbell's.  

Take a look at bootstrap's tables on [w3schools](http://www.w3schools.com/bootstrap/bootstrap_tables.asp).  See how you just have to add a class to the scores table?  Remember you can have more than one class on an element - so you can have a combination to get the effect you want.

Also, remember you can use chrome developer toolbar to experient.  Why don't you Inspect the scores table in chrome developer toolbar and add one of the tables attributes to it?  Experiment with different combinations to see how they differ.

Once you know what bootstrap classes you want to use, update [the scores table](https://github.com/Deadpool2468/minicoopers/blob/master/home.html#L51)

**Comment by batmal** [comment]
done!
