### ISSUE TITLE
Jumbotron

### ISSUE THREAD

**Issue by ghost** [Deadpool2468/minicoopers#12]
A jumbotron is a big box for highlight some special content or information.  They're an easy way to quickly convey a message.  And I (personally) think they look good.

As always, check out [w3schools](http://www.w3schools.com/bootstrap/bootstrap_jumbotron_header.asp) for guidance on how to create a jumbotron.

Try to create a jumbotron that says:-

> MINI COOPER COUNTS
> The objective of the game is to get the highest score

Make the first line huge, the second line slightly smaller - just like the example in w3schools.  Then you can remove the objective text from the "how to play" section.  Experiment with the capitals - it might not be necessary

**Comment by ghost** [comment]
@batmal can you do this one?  Thanks

**Comment by batmal** [comment]
ok!

is it easy

**Comment by batmal** [comment]
done
