### ISSUE TITLE
Clans

### ISSUE THREAD

**Issue by ghost** [Deadpool2468/minicoopers#2]
I think it would be fun if there were clans - ie Bruces, Campbells and Kerrs

**Comment by C1T1Z3N4** [comment]
that is a good idea

**Comment by ghost** [comment]
You'll need to:-
- Add a new column to the table header called 'Clan'
- For each clan, you'll need to add a new column that spans all the rows for the members.  Search w3cschools for rowspan
- You'll need to think about sorting, twice now (hint)

**Comment by ghost** [comment]
It's looking better but I think you need to group members together in their clan and introduce a clan-score:-
- Group all members together
- Order the clans (because you're a pedant)
- Order the members in the clan (see above)

When you've gone this you'll notice the clan name is repeated for each member.  This doesn't look great.  Instead it should be written once to group the members together.  That's why I hinted above you need to understand rowspan.  Rowspan allows you to create a column that 'spans' many rows.  In this case you'll need to write the clan name column once but have it span multiple rows (the number of members in each clan)
